# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text=b"Must start with 'https://'", verbose_name=b'Domain URL')),
            ],
        ),
    ]
